// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBvR_RvNuHaR-lYBJYU7PJai7qQ9xmG0',
    appId: '1:774853528624:web:309fc76cfd2ab7fd4f71f5',
    messagingSenderId: '774853528624',
    projectId: 'flutter-chat-app-50f65',
    authDomain: 'flutter-chat-app-50f65.firebaseapp.com',
    storageBucket: 'flutter-chat-app-50f65.appspot.com',
    measurementId: 'G-XBL71FFHJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSSnB2p57dEzpaWo7ShA8BriD0gVfuu4',
    appId: '1:774853528624:android:4fd8fad9aa24b5174f71f5',
    messagingSenderId: '774853528624',
    projectId: 'flutter-chat-app-50f65',
    storageBucket: 'flutter-chat-app-50f65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa5BiN81Lx2CnfeR3J43LDZhe43p_yJk4',
    appId: '1:774853528624:ios:7cb4c768ca945d674f71f5',
    messagingSenderId: '774853528624',
    projectId: 'flutter-chat-app-50f65',
    storageBucket: 'flutter-chat-app-50f65.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );
}
